exp: TokenClassification

mode: 
   - train

models: 
    hf_token_classification_model:
        - sentence-transformers/all-MiniLM-L6-v2
        
tokenizers:
        hf_tokenizer: 
            - bert-base-cased

trainfpath: ../NLP_FINAL/train_data/train.jsonl
validfpath: ../NLP_FINAL/train_data/valid.jsonl
modelfpath: ../NLP_FINAL/MiniLM

loadPretrained: False

numLabels: 2

epochs: 10

batchSize: 8

id2label:
    0: N
    1: A